// Generated by MyGeneration Version # (1.3.0.9)
using System;
using System.Collections.Generic;
using System.Text;
using Spring.Context.Support;
using Common.Logging;
using Legendigital.Framework.Common.BaseFramework.Entity.Tables;
using Legendigital.Framework.Common.BaseFramework.Bussiness.ServiceProxys.Tables.Container;
using Legendigital.Framework.Common.BaseFramework.Bussiness.ServiceProxys.Tables;
using Legendigital.Framework.Common.Data.NHibernate.DynamicQuery;

namespace Legendigital.Framework.Common.BaseFramework.Bussiness.Wrappers
{
    public partial class SystemTerminologyWrapper
    {
        #region Member

		internal static readonly ISystemTerminologyServiceProxy businessProxy = ((Legendigital.Framework.Common.BaseFramework.Bussiness.ServiceProxys.Tables.Container.BaseFrameworkServiceProxyContainer)(ContextRegistry.GetContext().GetObject("BaseFrameworkServiceProxyContainerIocID", typeof(Legendigital.Framework.Common.BaseFramework.Bussiness.ServiceProxys.Tables.Container.BaseFrameworkServiceProxyContainer)))).SystemTerminologyServiceProxyInstance;
	 
	 
        internal SystemTerminologyEntity entity;
		
		private static ILog logger = null;

        public static ILog Logger
        {
            get
            {
                if (logger == null)
                    logger = LogManager.GetLogger(typeof(SystemTerminologyWrapper));
                return logger;
            }
        }

        #endregion

        #region Construtor
        public SystemTerminologyWrapper() : this(new SystemTerminologyEntity())
        {
            
        }

        internal SystemTerminologyWrapper(SystemTerminologyEntity entityObj)
        {
            entity = entityObj;
        }
		#endregion
		
		#region Equals 和 HashCode 方法覆盖
		public override bool Equals(object obj)
        {
            if (obj == null && entity!=null)
            {
                if (entity.Id == 0)
                    return true;

                return false;
            }
            return entity.Equals(obj);
        }

        public override int GetHashCode()
        {
            return entity.GetHashCode();
        }
		#endregion
		
        #region 公共常量

		public static readonly string CLASS_FULL_NAME = "Legendigital.Framework.Common.BaseFramework.Entity.Tables.SystemTerminologyEntity";
		public static readonly string PROPERTY_NAME_ID = "Id";
		public static readonly string PROPERTY_NAME_NAME = "Name";
		public static readonly string PROPERTY_NAME_CODE = "Code";
		public static readonly string PROPERTY_NAME_DESCRIPTION = "Description";
		public static readonly string PROPERTY_NAME_TEXT = "Text";
		public static readonly string PROPERTY_NAME_LANGUAGETYPE = "LanguageType";
		
        #endregion


		#region Public Property
		/// <summary>
		/// 
		/// </summary>		
		public int Id
		{
			get
			{
				return entity.Id;
			}
			set
			{
				entity.Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>		
		public string Name
		{
			get
			{
				return entity.Name;
			}
			set
			{
				entity.Name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>		
		public string Code
		{
			get
			{
				return entity.Code;
			}
			set
			{
				entity.Code = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>		
		public string Description
		{
			get
			{
				return entity.Description;
			}
			set
			{
				entity.Description = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>		
		public string Text
		{
			get
			{
				return entity.Text;
			}
			set
			{
				entity.Text = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>		
		public string LanguageType
		{
			get
			{
				return entity.LanguageType;
			}
			set
			{
				entity.LanguageType = value;
			}
		}
		#endregion 





        #region "FKQuery"



        #endregion








        #region Static Common Data Operation
		
		internal static List<SystemTerminologyWrapper> ConvertToWrapperList(List<SystemTerminologyEntity> entitylist)
        {
            List<SystemTerminologyWrapper> list = new List<SystemTerminologyWrapper>();
            foreach (SystemTerminologyEntity lentity in entitylist)
            {
                list.Add(ConvertEntityToWrapper(lentity));
            }
            return list;
        }

		internal static List<SystemTerminologyWrapper> ConvertToWrapperList(IList<SystemTerminologyEntity> entitylist)
        {
            List<SystemTerminologyWrapper> list = new List<SystemTerminologyWrapper>();
            foreach (SystemTerminologyEntity lentity in entitylist)
            {
                list.Add(ConvertEntityToWrapper(lentity));
            }
            return list;
        }
		
		internal static List<SystemTerminologyEntity> ConvertToEntityList(List<SystemTerminologyWrapper> wrapperlist)
        {
            List<SystemTerminologyEntity> list = new List<SystemTerminologyEntity>();
            foreach (SystemTerminologyWrapper wrapper in wrapperlist)
            {
                list.Add(wrapper.entity);
            }
            return list;
        }

        internal static SystemTerminologyWrapper ConvertEntityToWrapper(SystemTerminologyEntity entity)
        {
            if (entity == null)
                return null;
				
            if (entity.Id == 0)
                return null;

            return new SystemTerminologyWrapper(entity);
        }
		
		#endregion

    }//End Class
}// End Namespace

