ALTER TABLE [dbo].[SystemPrivilegeInRoles]
    ADD CONSTRAINT [PK_SystemPrivilegeInRoles] PRIMARY KEY CLUSTERED ([PrivilegeRoleID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

