ALTER TABLE [dbo].[SystemUserGroup]
    ADD CONSTRAINT [PK_SystemUserGroup] PRIMARY KEY CLUSTERED ([Group_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

