ALTER TABLE [dbo].[SystemApplication]
    ADD CONSTRAINT [PK_SystemApplication] PRIMARY KEY CLUSTERED ([SystemApplication_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

