ALTER TABLE [dbo].[SystemUserGroupRoleRelation]
    ADD CONSTRAINT [PK_SystemUserGroupRole] PRIMARY KEY CLUSTERED ([UserGroupRole_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

