ALTER TABLE [dbo].[SystemRoleApplication]
    ADD CONSTRAINT [PK_SystemRoleApplication] PRIMARY KEY CLUSTERED ([SystemRoleApplication_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

