ALTER TABLE [dbo].[SystemRoleMenuRelation]
    ADD CONSTRAINT [PK_SystemRoleMenuRelation] PRIMARY KEY CLUSTERED ([MenuRole_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

