// Generated by MyGeneration Version # (1.3.0.9)
using System;
using System.Collections.Generic;
using System.Text;
using NHibernate.Criterion;
using Legendigital.Framework.Common.Data.NHibernate.DynamicQuery;
using Legendigital.Framework.Common.BaseFramework.Entity.Tables;
using Legendigital.Framework.Common.Data.NHibernate;


namespace Legendigital.Framework.Common.BaseFramework.Data.Tables
{
    public partial class SystemConfigDataObject : BaseNHibernateDataObject<SystemConfigEntity>
    {
				#region Expression Query Property (标准查询字段)
		public static readonly Property PROPERTY_SYSTEMCONFIGID = Property.ForName(SystemConfigEntity.PROPERTY_NAME_SYSTEMCONFIGID);
		public static readonly Property PROPERTY_CONFIGKEY = Property.ForName(SystemConfigEntity.PROPERTY_NAME_CONFIGKEY);
		public static readonly Property PROPERTY_CONFIGVALUE = Property.ForName(SystemConfigEntity.PROPERTY_NAME_CONFIGVALUE);
		public static readonly Property PROPERTY_CONFIGDESCRIPTION = Property.ForName(SystemConfigEntity.PROPERTY_NAME_CONFIGDESCRIPTION);
		public static readonly Property PROPERTY_SORTINDEX = Property.ForName(SystemConfigEntity.PROPERTY_NAME_SORTINDEX);
      
		#region 子类集合字段查询字段
	
		#endregion

		#endregion

		
		public override string[] PkPropertyName
        {
            get { return new string[] { "SystemConfigID" }; }
        }
		
		public override Type GetFieldTypeByFieldName(string fieldName)
        {
			switch (fieldName)
            {
                case "SystemConfigID":
                    return typeof (int);
                case "ConfigKey":
                    return typeof (string);
                case "ConfigValue":
                    return typeof (string);
                case "ConfigDescription":
                    return typeof (string);
                case "SortIndex":
                    return typeof (int);
          }
			return typeof(string);
        }
    }
}
