// Generated by MyGeneration Version # (1.3.0.9)
using System;
using System.Collections.Generic;
using System.Text;
using Legendigital.Framework.Common.Bussiness.Interfaces;
using Legendigital.Framework.Common.Data.Interfaces;
using Legendigital.Framework.Common.Data.NHibernate.DynamicQuery;
using Legendigital.Framework.Common.Bussiness.NHibernate;
using SPS.Data.Tables;
using SPS.Entity.Tables;
using SPS.Data.Tables.Container;
using SPS.Data.AdoNet;
using   SPS.Data.Tables.Container;




namespace SPS.Bussiness.ServiceProxys.Tables
{

    public interface ISPChannelFiltersServiceProxyDesigner
    {
		List<SPChannelFiltersEntity> FindAllByOrderByAndFilterAndChannelID(string orderByColumnName, bool isDesc,   SPChannelEntity _channelID, PageQueryParams pageQueryParams);
		List<SPChannelFiltersEntity> FindAllByChannelID(SPChannelEntity _channelID);
    }

    internal partial class SPChannelFiltersServiceProxy : BaseSpringNHibernateEntityServiceProxy<SPChannelFiltersEntity>
    {
		public DataObjectContainers DataObjectsContainerIocID { set; get; }
	
        public SPChannelFiltersDataObject SelfDataObj
        {
            set
            {
                selfDataObject = value;
            }
			get
            {
                return (SPChannelFiltersDataObject)selfDataObject;
            }
        }
	
		public List<SPChannelFiltersEntity> FindAllByOrderByAndFilterAndChannelID(string orderByColumnName, bool isDesc,  SPChannelEntity _channelID, PageQueryParams pageQueryParams)
        {
			return this.SelfDataObj.GetPageList_By_ChannelID_SPChannelEntity(orderByColumnName, isDesc,_channelID, pageQueryParams);
        }
		
		public List<SPChannelFiltersEntity> FindAllByChannelID(SPChannelEntity _channelID)
        {
			return this.SelfDataObj.GetList_By_ChannelID_SPChannelEntity(_channelID);
        }




        public AdoNetDataObject AdoNetDb { set; get; }		

		
    }
}
