// Generated by MyGeneration Version # (1.3.0.9)
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using Legendigital.Framework.Common.Bussiness.Interfaces;
using Legendigital.Framework.Common.Data.Interfaces;
using Legendigital.Framework.Common.Data.NHibernate.DynamicQuery;
using Legendigital.Framework.Common.Bussiness.NHibernate;
using SPS.Data.Tables;
using SPS.Entity.Tables;
using SPS.Data.Tables.Container;
using LD.SPPipeManage.Data.AdoNet;




namespace SPS.Bussiness.ServiceProxys.Tables
{

    public interface ISPRecordExtendInfoServiceProxyDesigner
    {
		List<SPRecordExtendInfoEntity> FindAllByOrderByAndFilterAndRecordID(string orderByColumnName, bool isDesc, int pageIndex, int pageSize,    SPRecordEntity _recordID, out int recordCount);
		List<SPRecordExtendInfoEntity> FindAllByRecordID(SPRecordEntity _recordID);
    }


    internal partial class SPRecordExtendInfoServiceProxy : BaseSpringNHibernateEntityServiceProxy<SPRecordExtendInfoEntity> , ISPRecordExtendInfoServiceProxyDesigner
    {
		public DataObjectContainers DataObjectsContainerIocID { set; get; }
	
        public SPRecordExtendInfoDataObject SelfDataObj
        {
            set
            {
                selfDataObject = value;
            }
			get
            {
                return (SPRecordExtendInfoDataObject)selfDataObject;
            }
        }
	
		public List<SPRecordExtendInfoEntity> FindAllByOrderByAndFilterAndRecordID(string orderByColumnName, bool isDesc,int pageIndex, int pageSize,     SPRecordEntity _recordID,  out int recordCount)
        {
			return this.SelfDataObj.GetPageList_By_SPRecordEntity(orderByColumnName, isDesc,pageIndex, pageSize,_recordID, out recordCount);
        }
		
		public List<SPRecordExtendInfoEntity> FindAllByRecordID(SPRecordEntity _recordID)
        {
			return this.SelfDataObj.GetList_By_SPRecordEntity(_recordID);
        }

		
		
        public AdoNetDataObject AdoNetDb { set; get; }		

		
    }
}
