// Generated by MyGeneration Version # (1.3.0.9)
using System;
using System.Collections.Generic;
using System.Text;
using NHibernate.Criterion;
using Legendigital.Framework.Common.Data.NHibernate.DynamicQuery;
using LD.SPPipeManage.Entity.Tables;
using Legendigital.Framework.Common.Data.NHibernate;

namespace LD.SPPipeManage.Data.Tables
{
    public partial class SPInterceptRateDataObject
    {
        public SPInterceptRateEntity FindRateByChannelIdAndClinetId(int channelId, int clientId)
        {
            NHibernateDynamicQueryGenerator<SPInterceptRateEntity> queryGenerator = this.GetNewQueryBuilder();

            queryGenerator.AddWhereClause(PROPERTY_CHANNELID.Eq(channelId));

            queryGenerator.AddWhereClause(PROPERTY_CLIENTID.Eq(clientId));

            return this.FindSingleEntityByQueryBuilder(queryGenerator);
        }
    }
}
