// --------------------------------------------------------------------------------------------------------------------
// <copyright company="foreveross" file="SPChannelSycnParamsEntity.cs">
//   Copyright (c) Foreveross Enterprises. All rights reserved.
// </copyright>
// <summary>
//   Generated by MyGeneration Version # (1.3.0.9)
// </summary>
// --------------------------------------------------------------------------------------------------------------------
using System;

namespace SPS.Entity.Tables
{
	[Serializable]
	public partial class SPChannelSycnParamsEntity
	{
	
	}
}
