// Generated by MyGeneration Version # (1.3.0.9)
using System;
using System.Collections.Generic;
using System.Text;
using Spring.Context.Support;
using Common.Logging;
using LD.SPPipeManage.Entity.Tables;
using LD.SPPipeManage.Bussiness.ServiceProxys.Tables.Container;
using LD.SPPipeManage.Bussiness.ServiceProxys.Tables;

namespace LD.SPPipeManage.Bussiness.Wrappers
{
    public partial class SPClientChannelSettingFiltersWrapper
    {
        #region Member

		internal static readonly ISPClientChannelSettingFiltersServiceProxy businessProxy = ((LD.SPPipeManage.Bussiness.ServiceProxys.Tables.Container.ServiceProxyContainer)(ContextRegistry.GetContext().GetObject("ServiceProxyContainerIocID", typeof(LD.SPPipeManage.Bussiness.ServiceProxys.Tables.Container.ServiceProxyContainer)))).SPClientChannelSettingFiltersServiceProxyInstance;
		//internal static readonly ISPClientChannelSettingFiltersServiceProxy businessProxy = ((ServiceProxyContainer)(ContextRegistry.GetContext().GetObject("ServiceProxyContainerIocID"))).SPClientChannelSettingFiltersServiceProxyInstance;

        internal SPClientChannelSettingFiltersEntity entity;
		
		private static ILog logger = null;

        public static ILog Logger
        {
            get
            {
                if (logger == null)
                    logger = LogManager.GetLogger(typeof(SPClientChannelSettingFiltersWrapper));
                return logger;
            }
        }

        #endregion

        #region Construtor
        public SPClientChannelSettingFiltersWrapper() : this(new SPClientChannelSettingFiltersEntity())
        {
            
        }

        internal SPClientChannelSettingFiltersWrapper(SPClientChannelSettingFiltersEntity entityObj)
        {
            entity = entityObj;
        }
		#endregion
		
		#region Equals 和 HashCode 方法覆盖
		public override bool Equals(object obj)
        {
            if (obj == null && entity!=null)
            {
                if (entity.Id == 0)
                    return true;

                return false;
            }
            return entity.Equals(obj);
        }

        public override int GetHashCode()
        {
            return entity.GetHashCode();
        }
		#endregion
		
        #region 公共常量

		public static readonly string CLASS_FULL_NAME = "LD.SPPipeManage.Entity.Tables.SPClientChannelSettingFiltersEntity";
		public static readonly string PROPERTY_NAME_ID = "Id";
		public static readonly string PROPERTY_NAME_PARAMSNAME = "ParamsName";
		public static readonly string PROPERTY_NAME_FILTERTYPE = "FilterType";
		public static readonly string PROPERTY_NAME_FILTERVALUE = "FilterValue";
		public static readonly string PROPERTY_NAME_ISENABLE = "IsEnable";
		public static readonly string PROPERTY_NAME_CLIENTCHANNELSETTINGID = "ClientChannelSettingID";
		
        #endregion


		#region Public Property
		/// <summary>
		/// 
		/// </summary>		
		public int Id
		{
			get
			{
				return entity.Id;
			}
			set
			{
				entity.Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>		
		public string ParamsName
		{
			get
			{
				return entity.ParamsName;
			}
			set
			{
				entity.ParamsName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>		
		public string FilterType
		{
			get
			{
				return entity.FilterType;
			}
			set
			{
				entity.FilterType = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>		
		public string FilterValue
		{
			get
			{
				return entity.FilterValue;
			}
			set
			{
				entity.FilterValue = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>		
		public bool? IsEnable
		{
			get
			{
				return entity.IsEnable;
			}
			set
			{
				entity.IsEnable = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>		
		public int? ClientChannelSettingID
		{
			get
			{
				return entity.ClientChannelSettingID;
			}
			set
			{
				entity.ClientChannelSettingID = value;
			}
		}
		#endregion 





        #region "FKQuery"



        #endregion








        #region Static Common Data Operation
		
		internal static List<SPClientChannelSettingFiltersWrapper> ConvertToWrapperList(List<SPClientChannelSettingFiltersEntity> entitylist)
        {
            List<SPClientChannelSettingFiltersWrapper> list = new List<SPClientChannelSettingFiltersWrapper>();
            foreach (SPClientChannelSettingFiltersEntity lentity in entitylist)
            {
                list.Add(ConvertEntityToWrapper(lentity));
            }
            return list;
        }

		internal static List<SPClientChannelSettingFiltersWrapper> ConvertToWrapperList(IList<SPClientChannelSettingFiltersEntity> entitylist)
        {
            List<SPClientChannelSettingFiltersWrapper> list = new List<SPClientChannelSettingFiltersWrapper>();
            foreach (SPClientChannelSettingFiltersEntity lentity in entitylist)
            {
                list.Add(ConvertEntityToWrapper(lentity));
            }
            return list;
        }
		
		internal static List<SPClientChannelSettingFiltersEntity> ConvertToEntityList(List<SPClientChannelSettingFiltersWrapper> wrapperlist)
        {
            List<SPClientChannelSettingFiltersEntity> list = new List<SPClientChannelSettingFiltersEntity>();
            foreach (SPClientChannelSettingFiltersWrapper wrapper in wrapperlist)
            {
                list.Add(wrapper.entity);
            }
            return list;
        }

        internal static SPClientChannelSettingFiltersWrapper ConvertEntityToWrapper(SPClientChannelSettingFiltersEntity entity)
        {
            if (entity == null)
                return null;
				
            if (entity.Id == 0)
                return null;

            return new SPClientChannelSettingFiltersWrapper(entity);
        }
		
		#endregion

    }//End Class
}// End Namespace

