// Generated by MyGeneration Version # (1.3.0.9)
using System;
using System.Collections.Generic;
using System.Text;
using Spring.Context.Support;
using Common.Logging;
using SPS.Entity.Tables;
using SPS.Bussiness.ServiceProxys.Tables.Container;
using SPS.Bussiness.ServiceProxys.Tables;
using Legendigital.Framework.Common.Data.NHibernate.DynamicQuery;

namespace SPS.Bussiness.Wrappers
{
    public partial class SPDayReportWrapper
    {
        #region Member

		internal static readonly ISPDayReportServiceProxy businessProxy = ((SPS.Bussiness.ServiceProxys.Tables.Container.ServiceProxyContainer)(ContextRegistry.GetContext().GetObject("ServiceProxyContainerIocID", typeof(SPS.Bussiness.ServiceProxys.Tables.Container.ServiceProxyContainer)))).SPDayReportServiceProxyInstance;
	 
	 
        internal SPDayReportEntity entity;
		
		private static ILog logger = null;

        public static ILog Logger
        {
            get
            {
                if (logger == null)
                    logger = LogManager.GetLogger(typeof(SPDayReportWrapper));
                return logger;
            }
        }

        #endregion

        #region Construtor
        public SPDayReportWrapper() : this(new SPDayReportEntity())
        {
            
        }

        internal SPDayReportWrapper(SPDayReportEntity entityObj)
        {
            entity = entityObj;
        }
		#endregion
		
		#region Equals 和 HashCode 方法覆盖
		public override bool Equals(object obj)
        {
            if (obj == null && entity!=null)
            {
                if (entity.Id == 0)
                    return true;

                return false;
            }
            return entity.Equals(obj);
        }

        public override int GetHashCode()
        {
            return entity.GetHashCode();
        }
		#endregion
		
      #region 公共常量

		public static readonly string CLASS_FULL_NAME = "SPS.Entity.Tables.SPDayReportEntity";
		public static readonly string PROPERTY_NAME_ID = "Id";
		public static readonly string PROPERTY_NAME_REPORTDATE = "ReportDate";
		public static readonly string PROPERTY_NAME_TOTALCOUNT = "TotalCount";
		public static readonly string PROPERTY_NAME_INTERCEPTCOUNT = "InterceptCount";
		public static readonly string PROPERTY_NAME_DOWNTOTALCOUNT = "DownTotalCount";
		public static readonly string PROPERTY_NAME_DOWNSUCCESS = "DownSuccess";
		public static readonly string PROPERTY_NAME_CLIENTID = "ClientID";
		public static readonly string PROPERTY_NAME_CHANNELID = "ChannelID";
		public static readonly string PROPERTY_NAME_CODEID = "CodeID";
		public static readonly string PROPERTY_NAME_UPERID = "UperID";
		
        #endregion
	
 
		#region clientID字段外键查询字段
        public static readonly string PROPERTY_CLIENTID_ALIAS_NAME = "ClientID_SPDayReportEntity_Alias";
		public static readonly string PROPERTY_CLIENTID_ID = "ClientID_SPDayReportEntity_Alias.Id";
		public static readonly string PROPERTY_CLIENTID_NAME = "ClientID_SPDayReportEntity_Alias.Name";
		public static readonly string PROPERTY_CLIENTID_DESCRIPTION = "ClientID_SPDayReportEntity_Alias.Description";
		public static readonly string PROPERTY_CLIENTID_USERID = "ClientID_SPDayReportEntity_Alias.UserID";
		public static readonly string PROPERTY_CLIENTID_ISDEFAULTCLIENT = "ClientID_SPDayReportEntity_Alias.IsDefaultClient";
		public static readonly string PROPERTY_CLIENTID_SYNCDATA = "ClientID_SPDayReportEntity_Alias.SyncData";
		public static readonly string PROPERTY_CLIENTID_SYCNRETRYTIMES = "ClientID_SPDayReportEntity_Alias.SycnRetryTimes";
		public static readonly string PROPERTY_CLIENTID_SYNCTYPE = "ClientID_SPDayReportEntity_Alias.SyncType";
		public static readonly string PROPERTY_CLIENTID_SYCNNOTINTERCEPTCOUNT = "ClientID_SPDayReportEntity_Alias.SycnNotInterceptCount";
		public static readonly string PROPERTY_CLIENTID_SYCNDATAURL = "ClientID_SPDayReportEntity_Alias.SycnDataUrl";
		public static readonly string PROPERTY_CLIENTID_SYCNOKMESSAGE = "ClientID_SPDayReportEntity_Alias.SycnOkMessage";
		public static readonly string PROPERTY_CLIENTID_SYCNFAILEDMESSAGE = "ClientID_SPDayReportEntity_Alias.SycnFailedMessage";
		public static readonly string PROPERTY_CLIENTID_ALIAS = "ClientID_SPDayReportEntity_Alias.Alias";
		public static readonly string PROPERTY_CLIENTID_INTERCEPTRATE = "ClientID_SPDayReportEntity_Alias.InterceptRate";
		public static readonly string PROPERTY_CLIENTID_DEFAULTPRICE = "ClientID_SPDayReportEntity_Alias.DefaultPrice";
		public static readonly string PROPERTY_CLIENTID_DEFAULTSHOWRECORDDAYS = "ClientID_SPDayReportEntity_Alias.DefaultShowRecordDays";
		public static readonly string PROPERTY_CLIENTID_CREATEBY = "ClientID_SPDayReportEntity_Alias.CreateBy";
		public static readonly string PROPERTY_CLIENTID_CREATEAT = "ClientID_SPDayReportEntity_Alias.CreateAt";
		public static readonly string PROPERTY_CLIENTID_LASTMODIFYBY = "ClientID_SPDayReportEntity_Alias.LastModifyBy";
		public static readonly string PROPERTY_CLIENTID_LASTMODIFYAT = "ClientID_SPDayReportEntity_Alias.LastModifyAt";
		public static readonly string PROPERTY_CLIENTID_LASTMODIFYCOMMENT = "ClientID_SPDayReportEntity_Alias.LastModifyComment";
		#endregion
		#region channelID字段外键查询字段
        public static readonly string PROPERTY_CHANNELID_ALIAS_NAME = "ChannelID_SPDayReportEntity_Alias";
		public static readonly string PROPERTY_CHANNELID_ID = "ChannelID_SPDayReportEntity_Alias.Id";
		public static readonly string PROPERTY_CHANNELID_NAME = "ChannelID_SPDayReportEntity_Alias.Name";
		public static readonly string PROPERTY_CHANNELID_CODE = "ChannelID_SPDayReportEntity_Alias.Code";
		public static readonly string PROPERTY_CHANNELID_DATAOKMESSAGE = "ChannelID_SPDayReportEntity_Alias.DataOkMessage";
		public static readonly string PROPERTY_CHANNELID_DATAFAILEDMESSAGE = "ChannelID_SPDayReportEntity_Alias.DataFailedMessage";
		public static readonly string PROPERTY_CHANNELID_DESCRIPTION = "ChannelID_SPDayReportEntity_Alias.Description";
		public static readonly string PROPERTY_CHANNELID_DATAADAPTERTYPE = "ChannelID_SPDayReportEntity_Alias.DataAdapterType";
		public static readonly string PROPERTY_CHANNELID_DATAADAPTERURL = "ChannelID_SPDayReportEntity_Alias.DataAdapterUrl";
		public static readonly string PROPERTY_CHANNELID_CHANNELTYPE = "ChannelID_SPDayReportEntity_Alias.ChannelType";
		public static readonly string PROPERTY_CHANNELID_IVRFEETIMETYPE = "ChannelID_SPDayReportEntity_Alias.IVRFeeTimeType";
		public static readonly string PROPERTY_CHANNELID_IVRTIMEFORMAT = "ChannelID_SPDayReportEntity_Alias.IVRTimeFormat";
		public static readonly string PROPERTY_CHANNELID_ISSTATEREPORT = "ChannelID_SPDayReportEntity_Alias.IsStateReport";
		public static readonly string PROPERTY_CHANNELID_STATEREPORTTYPE = "ChannelID_SPDayReportEntity_Alias.StateReportType";
		public static readonly string PROPERTY_CHANNELID_REPORTOKMESSAGE = "ChannelID_SPDayReportEntity_Alias.ReportOkMessage";
		public static readonly string PROPERTY_CHANNELID_REPORTFAILEDMESSAGE = "ChannelID_SPDayReportEntity_Alias.ReportFailedMessage";
		public static readonly string PROPERTY_CHANNELID_STATEREPORTPARAMNAME = "ChannelID_SPDayReportEntity_Alias.StateReportParamName";
		public static readonly string PROPERTY_CHANNELID_STATEREPORTPARAMVALUE = "ChannelID_SPDayReportEntity_Alias.StateReportParamValue";
		public static readonly string PROPERTY_CHANNELID_REQUESTTYPEPARAMNAME = "ChannelID_SPDayReportEntity_Alias.RequestTypeParamName";
		public static readonly string PROPERTY_CHANNELID_REQUESTTYPEPARAMSTATEREPORTVALUE = "ChannelID_SPDayReportEntity_Alias.RequestTypeParamStateReportValue";
		public static readonly string PROPERTY_CHANNELID_REQUESTTYPEPARAMDATAREPORTVALUE = "ChannelID_SPDayReportEntity_Alias.RequestTypeParamDataReportValue";
		public static readonly string PROPERTY_CHANNELID_HASFILTERS = "ChannelID_SPDayReportEntity_Alias.HasFilters";
		public static readonly string PROPERTY_CHANNELID_ISMONITORREQUEST = "ChannelID_SPDayReportEntity_Alias.IsMonitorRequest";
		public static readonly string PROPERTY_CHANNELID_ISLOGREQUEST = "ChannelID_SPDayReportEntity_Alias.IsLogRequest";
		public static readonly string PROPERTY_CHANNELID_ISPARAMSCONVERT = "ChannelID_SPDayReportEntity_Alias.IsParamsConvert";
		public static readonly string PROPERTY_CHANNELID_ISAUTOLINKID = "ChannelID_SPDayReportEntity_Alias.IsAutoLinkID";
		public static readonly string PROPERTY_CHANNELID_AUTOLINKIDFIELDS = "ChannelID_SPDayReportEntity_Alias.AutoLinkIDFields";
		public static readonly string PROPERTY_CHANNELID_LOGREQUESTTYPE = "ChannelID_SPDayReportEntity_Alias.LogRequestType";
		public static readonly string PROPERTY_CHANNELID_PRICE = "ChannelID_SPDayReportEntity_Alias.Price";
		public static readonly string PROPERTY_CHANNELID_DEFAULTRATE = "ChannelID_SPDayReportEntity_Alias.DefaultRate";
		public static readonly string PROPERTY_CHANNELID_CHANNELDETAILINFO = "ChannelID_SPDayReportEntity_Alias.ChannelDetailInfo";
		public static readonly string PROPERTY_CHANNELID_UPPERID = "ChannelID_SPDayReportEntity_Alias.UpperID";
		public static readonly string PROPERTY_CHANNELID_CHANNELSTATUS = "ChannelID_SPDayReportEntity_Alias.ChannelStatus";
		public static readonly string PROPERTY_CHANNELID_ISDISABLE = "ChannelID_SPDayReportEntity_Alias.IsDisable";
		public static readonly string PROPERTY_CHANNELID_CREATEBY = "ChannelID_SPDayReportEntity_Alias.CreateBy";
		public static readonly string PROPERTY_CHANNELID_CREATEAT = "ChannelID_SPDayReportEntity_Alias.CreateAt";
		public static readonly string PROPERTY_CHANNELID_LASTMODIFYBY = "ChannelID_SPDayReportEntity_Alias.LastModifyBy";
		public static readonly string PROPERTY_CHANNELID_LASTMODIFYAT = "ChannelID_SPDayReportEntity_Alias.LastModifyAt";
		public static readonly string PROPERTY_CHANNELID_LASTMODIFYCOMMENT = "ChannelID_SPDayReportEntity_Alias.LastModifyComment";
		#endregion
		#region codeID字段外键查询字段
        public static readonly string PROPERTY_CODEID_ALIAS_NAME = "CodeID_SPDayReportEntity_Alias";
		public static readonly string PROPERTY_CODEID_ID = "CodeID_SPDayReportEntity_Alias.Id";
		public static readonly string PROPERTY_CODEID_NAME = "CodeID_SPDayReportEntity_Alias.Name";
		public static readonly string PROPERTY_CODEID_DESCRIPTION = "CodeID_SPDayReportEntity_Alias.Description";
		public static readonly string PROPERTY_CODEID_CODE = "CodeID_SPDayReportEntity_Alias.Code";
		public static readonly string PROPERTY_CODEID_CHANNELID = "CodeID_SPDayReportEntity_Alias.ChannelID";
		public static readonly string PROPERTY_CODEID_MO = "CodeID_SPDayReportEntity_Alias.Mo";
		public static readonly string PROPERTY_CODEID_MOTYPE = "CodeID_SPDayReportEntity_Alias.MOType";
		public static readonly string PROPERTY_CODEID_ORDERINDEX = "CodeID_SPDayReportEntity_Alias.OrderIndex";
		public static readonly string PROPERTY_CODEID_SPCODE = "CodeID_SPDayReportEntity_Alias.SPCode";
		public static readonly string PROPERTY_CODEID_PROVINCE = "CodeID_SPDayReportEntity_Alias.Province";
		public static readonly string PROPERTY_CODEID_DISABLECITY = "CodeID_SPDayReportEntity_Alias.DisableCity";
		public static readonly string PROPERTY_CODEID_ISDIABLE = "CodeID_SPDayReportEntity_Alias.IsDiable";
		public static readonly string PROPERTY_CODEID_SPTYPE = "CodeID_SPDayReportEntity_Alias.SPType";
		public static readonly string PROPERTY_CODEID_CODELENGTH = "CodeID_SPDayReportEntity_Alias.CodeLength";
		public static readonly string PROPERTY_CODEID_DAYLIMIT = "CodeID_SPDayReportEntity_Alias.DayLimit";
		public static readonly string PROPERTY_CODEID_MONTHLIMIT = "CodeID_SPDayReportEntity_Alias.MonthLimit";
		public static readonly string PROPERTY_CODEID_PRICE = "CodeID_SPDayReportEntity_Alias.Price";
		public static readonly string PROPERTY_CODEID_SENDTEXT = "CodeID_SPDayReportEntity_Alias.SendText";
		public static readonly string PROPERTY_CODEID_HASFILTERS = "CodeID_SPDayReportEntity_Alias.HasFilters";
		public static readonly string PROPERTY_CODEID_CREATEBY = "CodeID_SPDayReportEntity_Alias.CreateBy";
		public static readonly string PROPERTY_CODEID_CREATEAT = "CodeID_SPDayReportEntity_Alias.CreateAt";
		public static readonly string PROPERTY_CODEID_LASTMODIFYBY = "CodeID_SPDayReportEntity_Alias.LastModifyBy";
		public static readonly string PROPERTY_CODEID_LASTMODIFYAT = "CodeID_SPDayReportEntity_Alias.LastModifyAt";
		public static readonly string PROPERTY_CODEID_LASTMODIFYCOMMENT = "CodeID_SPDayReportEntity_Alias.LastModifyComment";
		public static readonly string PROPERTY_CODEID_HASPARAMSCONVERT = "CodeID_SPDayReportEntity_Alias.HasParamsConvert";
		#endregion
		#region uperID字段外键查询字段
        public static readonly string PROPERTY_UPERID_ALIAS_NAME = "UperID_SPDayReportEntity_Alias";
		public static readonly string PROPERTY_UPERID_ID = "UperID_SPDayReportEntity_Alias.Id";
		public static readonly string PROPERTY_UPERID_NAME = "UperID_SPDayReportEntity_Alias.Name";
		public static readonly string PROPERTY_UPERID_CODE = "UperID_SPDayReportEntity_Alias.Code";
		public static readonly string PROPERTY_UPERID_DESCRIPTION = "UperID_SPDayReportEntity_Alias.Description";
		public static readonly string PROPERTY_UPERID_CREATEBY = "UperID_SPDayReportEntity_Alias.CreateBy";
		public static readonly string PROPERTY_UPERID_CREATEAT = "UperID_SPDayReportEntity_Alias.CreateAt";
		public static readonly string PROPERTY_UPERID_LASTMODIFYBY = "UperID_SPDayReportEntity_Alias.LastModifyBy";
		public static readonly string PROPERTY_UPERID_LASTMODIFYAT = "UperID_SPDayReportEntity_Alias.LastModifyAt";
		public static readonly string PROPERTY_UPERID_LASTMODIFYCOMMENT = "UperID_SPDayReportEntity_Alias.LastModifyComment";
		#endregion
      	
	
	
		 
		
		
		
		


		#region Public Property
		/// <summary>
		/// 
		/// </summary>		
		public int Id
		{
			get
			{
				return entity.Id;
			}
			set
			{
				entity.Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>		
		public DateTime ReportDate
		{
			get
			{
				return entity.ReportDate;
			}
			set
			{
				entity.ReportDate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>		
		public int TotalCount
		{
			get
			{
				return entity.TotalCount;
			}
			set
			{
				entity.TotalCount = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>		
		public int InterceptCount
		{
			get
			{
				return entity.InterceptCount;
			}
			set
			{
				entity.InterceptCount = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>		
		public int DownTotalCount
		{
			get
			{
				return entity.DownTotalCount;
			}
			set
			{
				entity.DownTotalCount = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>		
		public int DownSuccess
		{
			get
			{
				return entity.DownSuccess;
			}
			set
			{
				entity.DownSuccess = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>		
		public SPSClientWrapper ClientID
		{
			get
			{
				return SPSClientWrapper.ConvertEntityToWrapper(entity.ClientID) ;
			}
			set
			{
				entity.ClientID = ((value == null) ? null : value.entity);
			}
		}
		/// <summary>
		/// 
		/// </summary>		
		public SPChannelWrapper ChannelID
		{
			get
			{
				return SPChannelWrapper.ConvertEntityToWrapper(entity.ChannelID) ;
			}
			set
			{
				entity.ChannelID = ((value == null) ? null : value.entity);
			}
		}
		/// <summary>
		/// 
		/// </summary>		
		public SPCodeWrapper CodeID
		{
			get
			{
				return SPCodeWrapper.ConvertEntityToWrapper(entity.CodeID) ;
			}
			set
			{
				entity.CodeID = ((value == null) ? null : value.entity);
			}
		}
		/// <summary>
		/// 
		/// </summary>		
		public SPUpperWrapper UperID
		{
			get
			{
				return SPUpperWrapper.ConvertEntityToWrapper(entity.UperID) ;
			}
			set
			{
				entity.UperID = ((value == null) ? null : value.entity);
			}
		}
		#endregion 





        #region "FKQuery"
		
        public static List<SPDayReportWrapper> FindAllByOrderByAndFilterAndClientID(string orderByColumnName, bool isDesc,   SPSClientWrapper clientID,  PageQueryParams pageQueryParams)
        {
            return ConvertToWrapperList(businessProxy.FindAllByOrderByAndFilterAndClientID(orderByColumnName, isDesc,   clientID.entity, pageQueryParams));
        }

        public static List<SPDayReportWrapper> FindAllByClientID(SPSClientWrapper clientID)
        {
            return ConvertToWrapperList(businessProxy.FindAllByClientID(clientID.entity));
        }
		
		
        public static List<SPDayReportWrapper> FindAllByOrderByAndFilterAndChannelID(string orderByColumnName, bool isDesc,   SPChannelWrapper channelID,  PageQueryParams pageQueryParams)
        {
            return ConvertToWrapperList(businessProxy.FindAllByOrderByAndFilterAndChannelID(orderByColumnName, isDesc,   channelID.entity, pageQueryParams));
        }

        public static List<SPDayReportWrapper> FindAllByChannelID(SPChannelWrapper channelID)
        {
            return ConvertToWrapperList(businessProxy.FindAllByChannelID(channelID.entity));
        }
		
		
        public static List<SPDayReportWrapper> FindAllByOrderByAndFilterAndCodeID(string orderByColumnName, bool isDesc,   SPCodeWrapper codeID,  PageQueryParams pageQueryParams)
        {
            return ConvertToWrapperList(businessProxy.FindAllByOrderByAndFilterAndCodeID(orderByColumnName, isDesc,   codeID.entity, pageQueryParams));
        }

        public static List<SPDayReportWrapper> FindAllByCodeID(SPCodeWrapper codeID)
        {
            return ConvertToWrapperList(businessProxy.FindAllByCodeID(codeID.entity));
        }
		
		
        public static List<SPDayReportWrapper> FindAllByOrderByAndFilterAndUperID(string orderByColumnName, bool isDesc,   SPUpperWrapper uperID,  PageQueryParams pageQueryParams)
        {
            return ConvertToWrapperList(businessProxy.FindAllByOrderByAndFilterAndUperID(orderByColumnName, isDesc,   uperID.entity, pageQueryParams));
        }

        public static List<SPDayReportWrapper> FindAllByUperID(SPUpperWrapper uperID)
        {
            return ConvertToWrapperList(businessProxy.FindAllByUperID(uperID.entity));
        }
		



        #endregion








        #region Static Common Data Operation
		
		internal static List<SPDayReportWrapper> ConvertToWrapperList(List<SPDayReportEntity> entitylist)
        {
            List<SPDayReportWrapper> list = new List<SPDayReportWrapper>();
            foreach (SPDayReportEntity lentity in entitylist)
            {
                list.Add(ConvertEntityToWrapper(lentity));
            }
            return list;
        }

		internal static List<SPDayReportWrapper> ConvertToWrapperList(IList<SPDayReportEntity> entitylist)
        {
            List<SPDayReportWrapper> list = new List<SPDayReportWrapper>();
            foreach (SPDayReportEntity lentity in entitylist)
            {
                list.Add(ConvertEntityToWrapper(lentity));
            }
            return list;
        }
		
		internal static List<SPDayReportEntity> ConvertToEntityList(List<SPDayReportWrapper> wrapperlist)
        {
            List<SPDayReportEntity> list = new List<SPDayReportEntity>();
            foreach (SPDayReportWrapper wrapper in wrapperlist)
            {
                list.Add(wrapper.entity);
            }
            return list;
        }

        internal static SPDayReportWrapper ConvertEntityToWrapper(SPDayReportEntity entity)
        {
            if (entity == null)
                return null;
				
            if (entity.Id == 0)
                return null;

            return new SPDayReportWrapper(entity);
        }
		
		#endregion

    }//End Class
}// End Namespace

