// Generated by MyGeneration Version # (1.3.0.9)
using System;
using System.Collections.Generic;
using System.Text;
using Legendigital.Framework.Common.Bussiness.Interfaces;
using Legendigital.Framework.Common.Data.Interfaces;
using Legendigital.Framework.Common.Bussiness.NHibernate;
using LD.SPPipeManage.Data.Tables;
using LD.SPPipeManage.Entity.Tables;


namespace LD.SPPipeManage.Bussiness.ServiceProxys.Tables
{
	public interface ISPPhoneAreaServiceProxy : IBaseSpringNHibernateEntityServiceProxy<SPPhoneAreaEntity>
    {
	    List<SPPhoneAreaEntity> GetPhoneCity(string phone);
    }

    internal partial class SPPhoneAreaServiceProxy : ISPPhoneAreaServiceProxy
    {
        public List<SPPhoneAreaEntity> GetPhoneCity(string phone)
        {
            return this.SelfDataObj.GetPhoneCityByPhonePrefix(phone);
        }
 
    }
}
