CREATE TABLE [dbo].[SystemEmployee] (
    [ID]                  INT             IDENTITY (1, 1) NOT NULL,
    [OrganizationID]      INT             NULL,
    [Number]              NVARCHAR (50)   NULL,
    [FristName]           NVARCHAR (50)   NULL,
    [MiddleName]          NVARCHAR (50)   NULL,
    [LastName]            NVARCHAR (50)   NULL,
    [FullName]            NVARCHAR (50)   NULL,
    [Office1PhoneNumber]  NVARCHAR (50)   NULL,
    [Office2PhoneNumber]  NVARCHAR (50)   NULL,
    [Home1PhoneNumber]    NVARCHAR (50)   NULL,
    [Home2PhoneNumber]    NVARCHAR (50)   NULL,
    [Mobile1PhoneNumber]  NVARCHAR (50)   NULL,
    [Mobile2PhoneNumber]  NVARCHAR (50)   NULL,
    [Sex]                 INT             NULL,
    [Age]                 INT             NULL,
    [Birthday]            DATETIME        NULL,
    [HomePage]            NVARCHAR (200)  NULL,
    [Comments]            NVARCHAR (2000) NULL,
    [DefaultDepartmentID] INT             NULL,
    [DefaultPostID]       INT             NULL,
    [UserID]              INT             NULL,
    [Email2]              NVARCHAR (50)   NULL,
    [Email1]              NVARCHAR (50)   NULL,
    [IsActive]            BIT             NULL,
    [Status]              NVARCHAR (50)   NULL,
    [CreateBy]            INT             NULL,
    [CreateAt]            DATETIME        NULL,
    [LastModifyBy]        INT             NULL,
    [LastModifyAt]        DATETIME        NULL,
    [LastModifyComment]   NVARCHAR (300)  NULL,
    CONSTRAINT [PK_SystemEmployee] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SystemEmployee_SystemOrganization] FOREIGN KEY ([OrganizationID]) REFERENCES [dbo].[SystemOrganization] ([ID]) ON DELETE CASCADE
);

