//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legendigital.Common.Web.Moudles.SPS.ClientChannelSettings {
    
    
    public partial class UCSPClientChannelParamsEdit {
        
        /// <summary>
        /// winSPSendClientParamsEdit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Window winSPSendClientParamsEdit;
        
        /// <summary>
        /// fitLayoutMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FitLayout fitLayoutMain;
        
        /// <summary>
        /// formPanelSPSendClientParamsEdit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormPanel formPanelSPSendClientParamsEdit;
        
        /// <summary>
        /// FormLayoutSPSendClientParams control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayoutSPSendClientParams;
        
        /// <summary>
        /// hidId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Hidden hidId;
        
        /// <summary>
        /// lblClientName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Label lblClientName;
        
        /// <summary>
        /// txtName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.TextField txtName;
        
        /// <summary>
        /// txtTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.TextField txtTitle;
        
        /// <summary>
        /// txtDescription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.TextArea txtDescription;
        
        /// <summary>
        /// chkIsEnable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Checkbox chkIsEnable;
        
        /// <summary>
        /// chkIsRequired control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Checkbox chkIsRequired;
        
        /// <summary>
        /// cmbMappingParams control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ComboBox cmbMappingParams;
        
        /// <summary>
        /// btnSaveSPSendClientParams control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button btnSaveSPSendClientParams;
        
        /// <summary>
        /// btnCancelSPSendClientParams control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button btnCancelSPSendClientParams;
    }
}
