// Generated by MyGeneration Version # (1.3.0.9)
using System;
using System.Collections.Generic;
using System.Text;
using LD.SPPipeManage.Bussiness.Wrappers;
using Legendigital.Framework.Common.Bussiness.Interfaces;
using Legendigital.Framework.Common.Data.Interfaces;
using Legendigital.Framework.Common.Bussiness.NHibernate;
using LD.SPPipeManage.Data.Tables;
using LD.SPPipeManage.Entity.Tables;
using Spring.Transaction.Interceptor;


namespace LD.SPPipeManage.Bussiness.ServiceProxys.Tables
{
    public interface ISPClientServiceProxy : IBaseSpringNHibernateEntityServiceProxy<SPClientEntity>, ISPClientServiceProxyDesigner
    {
	    List<SPSendClientParamsEntity> GetAllEnableParams(SPClientEntity entity);
	    List<SPClientEntity> FindByChannelID(int cid);
	    SPClientEntity GetClientByUserID(int userId);
        void CloneChannelParams(int channelId, SPClientEntity entity);
        void QuickAdd(string loginID, string code, SPChannelEntity channelEntity, int mainloginuserID, List<CodeUserID> codeUserIds);
    }

    internal partial class SPClientServiceProxy : ISPClientServiceProxy
    {
        public List<SPSendClientParamsEntity> GetAllEnableParams(SPClientEntity entity)
        {
            return this.DataObjectsContainerIocID.SPSendClientParamsDataObjectInstance.GetAllEnableParams(entity);
        }

        public List<SPClientEntity> FindByChannelID(int cid)
        {
            SPChannelEntity channelEntity = this.DataObjectsContainerIocID.SPChannelDataObjectInstance.Load(cid);

            List<SPClientChannelSettingEntity> settings = this.DataObjectsContainerIocID.SPClientChannelSettingDataObjectInstance.GetSettingByChannel(channelEntity);

            List<SPClientEntity> clientEntities = new List<SPClientEntity>();

            foreach (SPClientChannelSettingEntity spClientEntity in settings)
            {
                if(!clientEntities.Contains(spClientEntity.ClinetID))
                {
                    clientEntities.Add(spClientEntity.ClinetID);
                }
            }

            return clientEntities;
        }

        [Transaction(ReadOnly = false)]
        public void CloneChannelParams(int channelId, SPClientEntity entity)
        {
            SPChannelEntity channelEntity = this.DataObjectsContainerIocID.SPChannelDataObjectInstance.Load(channelId);

            List<SPChannelParamsEntity> channelParamsEntities =
                this.DataObjectsContainerIocID.SPChannelParamsDataObjectInstance.GetAllEnableParams(channelEntity);


            List<SPSendClientParamsEntity> sendClientParamsEntities =
                this.DataObjectsContainerIocID.SPSendClientParamsDataObjectInstance.GetAllEnableParams(entity);

            foreach (SPSendClientParamsEntity spSendClientParamsEntity in sendClientParamsEntities)
            {
                this.DataObjectsContainerIocID.SPSendClientParamsDataObjectInstance.Delete(spSendClientParamsEntity);
            }

            foreach (SPChannelParamsEntity channelParamsEntity in channelParamsEntities)
            {
                SPSendClientParamsEntity spSendClientParamsEntity = new SPSendClientParamsEntity();
                spSendClientParamsEntity.ClientID = entity;
                spSendClientParamsEntity.Name = channelParamsEntity.Name;
                spSendClientParamsEntity.Title = channelParamsEntity.Title;
                spSendClientParamsEntity.Description = channelParamsEntity.Description;
                spSendClientParamsEntity.IsEnable = channelParamsEntity.IsEnable;
                spSendClientParamsEntity.IsRequired = channelParamsEntity.IsRequired;
                spSendClientParamsEntity.MappingParams = channelParamsEntity.ParamsMappingName;
                this.DataObjectsContainerIocID.SPSendClientParamsDataObjectInstance.Save(spSendClientParamsEntity);
            }
        }
        [Transaction(ReadOnly = false)]
        public void QuickAdd(string loginID, string code, SPChannelEntity channelEntity, int mainloginuserID, List<CodeUserID> codeUserIds)
        {
            SPClientEntity mainclientEntity = new SPClientEntity();
            mainclientEntity.Name = channelEntity.Name + loginID;
            mainclientEntity.Description = channelEntity.Name + loginID;
            mainclientEntity.UserID = mainloginuserID;

            this.DataObjectsContainerIocID.SPClientDataObjectInstance.Save(mainclientEntity);

            SPClientChannelSettingEntity mainChannelClient = new SPClientChannelSettingEntity();

            mainChannelClient.Name = channelEntity.Name + loginID;
            mainChannelClient.Description = channelEntity.Name + loginID;
            mainChannelClient.ChannelID = channelEntity;
            mainChannelClient.ClinetID = mainclientEntity;
            mainChannelClient.InterceptRate = 0;
            mainChannelClient.OrderIndex = 1;
            mainChannelClient.UpRate = 0;
            mainChannelClient.DownRate = 0;
            mainChannelClient.CommandColumn = "ywid";
            mainChannelClient.CommandType = "3";
            mainChannelClient.CommandCode = code;
            mainChannelClient.SyncData = false;

            this.DataObjectsContainerIocID.SPClientChannelSettingDataObjectInstance.Save(mainChannelClient);

            foreach (CodeUserID codeUserId in codeUserIds)
            {
                SPClientEntity subClientEntity = new SPClientEntity();
                subClientEntity.Name = channelEntity.Name + loginID + codeUserId.Code;
                subClientEntity.Description = channelEntity.Name + loginID + codeUserId.Code;
                subClientEntity.UserID = codeUserId.UserID;

                this.DataObjectsContainerIocID.SPClientDataObjectInstance.Save(subClientEntity);


                SPClientChannelSettingEntity subChannelClient = new SPClientChannelSettingEntity();

                subChannelClient.Name = channelEntity.Name + loginID + codeUserId.Code;
                subChannelClient.Description = channelEntity.Name + loginID + codeUserId.Code;
                subChannelClient.ChannelID = channelEntity;
                subChannelClient.ClinetID = subClientEntity;
                subChannelClient.InterceptRate = 0;
                subChannelClient.OrderIndex = 2;
                subChannelClient.UpRate = 0;
                subChannelClient.DownRate = 0;
                subChannelClient.CommandColumn = "ywid";
                subChannelClient.CommandType = "3";
                subChannelClient.CommandCode = code + codeUserId.Code;
                subChannelClient.SyncData = false;

                this.DataObjectsContainerIocID.SPClientChannelSettingDataObjectInstance.Save(subChannelClient);           
            }


        }


        public SPClientEntity GetClientByUserID(int userId)
        {
            return this.SelfDataObj.GetClientByUserID(userId);
        }
    }
}
