ALTER TABLE [dbo].[SystemMenu]
    ADD CONSTRAINT [PK_SystemMenu] PRIMARY KEY CLUSTERED ([Menu_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

