ALTER TABLE [dbo].[SystemShortMessage]
    ADD CONSTRAINT [PK_SystemShortMessage] PRIMARY KEY CLUSTERED ([ShortMessage_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

