ALTER TABLE [dbo].[SystemLog]
    ADD CONSTRAINT [PK_SystemLog] PRIMARY KEY CLUSTERED ([Log_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

