ALTER TABLE [dbo].[SystemUserProfilePropertys]
    ADD CONSTRAINT [PK_SystemProfile] PRIMARY KEY CLUSTERED ([Property_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

