ALTER TABLE [dbo].[SystemMoudleField]
    ADD CONSTRAINT [PK_SystemMoudleField] PRIMARY KEY CLUSTERED ([SystemMoudleField_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

