ALTER TABLE [dbo].[SystemPrivilege]
    ADD CONSTRAINT [PK_SystemPrivilege] PRIMARY KEY CLUSTERED ([Privilege_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

