ALTER TABLE [dbo].[SystemViewItem]
    ADD CONSTRAINT [PK_SystemViewItem] PRIMARY KEY CLUSTERED ([SystemViewItem_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

