ALTER TABLE [dbo].[SystemResources]
    ADD CONSTRAINT [PK_SystemResources] PRIMARY KEY CLUSTERED ([Resources_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

