ALTER TABLE [dbo].[SystemUserGroupUserRelation]
    ADD CONSTRAINT [PK_UserGroupUserRelation] PRIMARY KEY CLUSTERED ([UserGroupUserID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

