CREATE TABLE [dbo].[SPChannel] (
    [ID]                               INT             IDENTITY (1, 1) NOT NULL,
    [Name]                             NVARCHAR (50)   NOT NULL,
    [Code]                             NVARCHAR (50)   NOT NULL,
    [DataOkMessage]                    NVARCHAR (200)  NOT NULL,
    [DataFailedMessage]                NVARCHAR (200)  NOT NULL,
    [Description]                      NVARCHAR (2000) NOT NULL,
    [DataAdapterType]                  NVARCHAR (50)   NOT NULL,
    [DataAdapterUrl]                   NVARCHAR (200)  NOT NULL,
    [ChannelType]                      NVARCHAR (20)   NOT NULL,
    [IVRFeeTimeType]                   NVARCHAR (20)   NULL,
    [IVRTimeFormat]                    NVARCHAR (20)   NULL,
    [IsStateReport]                    BIT             NOT NULL,
    [StateReportType]                  NVARCHAR (20)   NOT NULL,
    [ReportOkMessage]                  NVARCHAR (200)  NOT NULL,
    [ReportFailedMessage]              NVARCHAR (200)  NOT NULL,
    [StateReportParamName]             NVARCHAR (20)   NOT NULL,
    [StateReportParamValue]            NVARCHAR (20)   NOT NULL,
    [RequestTypeParamName]             NVARCHAR (20)   NOT NULL,
    [RequestTypeParamStateReportValue] NVARCHAR (20)   NOT NULL,
    [RequestTypeParamDataReportValue]  NVARCHAR (20)   NOT NULL,
    [HasFilters]                       BIT             NOT NULL,
    [IsMonitorRequest]                 BIT             NOT NULL,
    [IsLogRequest]                     BIT             NOT NULL,
    [IsParamsConvert]                  BIT             NOT NULL,
    [IsAutoLinkID]                     BIT             NOT NULL,
    [AutoLinkIDFields]                 NVARCHAR (300)  NOT NULL,
    [LogRequestType]                   NVARCHAR (20)   NULL,
    [Price]                            DECIMAL (18)    NULL,
    [DefaultRate]                      DECIMAL (18)    NULL,
    [ChannelDetailInfo]                NTEXT           NULL,
    [UpperID]                          INT             NULL,
    [ChannelStatus]                    NVARCHAR (20)   NULL,
    [IsDisable]                        BIT             NOT NULL,
    [CreateBy]                         INT             NULL,
    [CreateAt]                         DATETIME        NULL,
    [LastModifyBy]                     INT             NULL,
    [LastModifyAt]                     DATETIME        NULL,
    [LastModifyComment]                NVARCHAR (300)  NULL,
    CONSTRAINT [PK_SPCHANNEL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SPCHANNE_REFERENCE_SPUPPER] FOREIGN KEY ([UpperID]) REFERENCES [dbo].[SPUpper] ([ID]) ON DELETE SET NULL
);

