CREATE TABLE [dbo].[SPCode] (
    [ID]                     INT             IDENTITY (1, 1) NOT NULL,
    [Name]                   NVARCHAR (50)   NOT NULL,
    [Description]            NVARCHAR (200)  NOT NULL,
    [Code]                   NVARCHAR (200)  NOT NULL,
    [CodeType]               NVARCHAR (50)   NULL,
    [ChannelID]              INT             NOT NULL,
    [MO]                     NVARCHAR (50)   NOT NULL,
    [MOType]                 NVARCHAR (50)   NOT NULL,
    [MOLength]               INT             NULL,
    [OrderIndex]             INT             NOT NULL,
    [SPCode]                 NVARCHAR (50)   NOT NULL,
    [SPCodeType]             NVARCHAR (50)   NULL,
    [SPCodeLength]           INT             NULL,
    [HasFilters]             BIT             CONSTRAINT [DF_SPCode_HasFilters] DEFAULT ((0)) NOT NULL,
    [HasParamsConvert]       BIT             CONSTRAINT [DF_SPCode_HasParamsConvert] DEFAULT ((0)) NOT NULL,
    [IsDiable]               BIT             CONSTRAINT [DF_SPCode_IsDiable] DEFAULT ((0)) NOT NULL,
    [Price]                  DECIMAL (18, 2) NULL,
    [OperationType]          NVARCHAR (50)   NULL,
    [HasDayTotalLimit]       BIT             CONSTRAINT [DF_SPCode_HasDayTotalLimit] DEFAULT ((0)) NOT NULL,
    [DayTotalLimitCount]     INT             CONSTRAINT [DF_SPCode_DayTotalLimitCount] DEFAULT ((0)) NOT NULL,
    [HasPhoneLimit]          BIT             CONSTRAINT [DF_SPCode_HasPhoneLimit] DEFAULT ((0)) NOT NULL,
    [PhoneLimitDayCount]     INT             CONSTRAINT [DF_SPCode_PhoneLimit] DEFAULT ((0)) NOT NULL,
    [PhoneLimitMonthCount]   INT             CONSTRAINT [DF_SPCode_PhoneLimitMonthCount] DEFAULT ((0)) NOT NULL,
    [PhoneLimitType]         INT             CONSTRAINT [DF_SPCode_PhoneLimitType] DEFAULT ((1)) NOT NULL,
    [LimitProvince]          BIT             CONSTRAINT [DF_SPCode_LimitProvince] DEFAULT ((0)) NULL,
    [LimitProvinceArea]      NVARCHAR (200)  NULL,
    [ParentID]               INT             NULL,
    [IsMatchCase]            BIT             CONSTRAINT [DF_SPCode_IsMatchCase] DEFAULT ((0)) NULL,
    [IsDayTimeLimit]         BIT             NULL,
    [DayTimeLimitRangeStart] DATETIME        NULL,
    [DayTimeLimitRangeEnd]   DATETIME        NULL,
    [ChannelStatus]          NVARCHAR (20)   NULL,
    [CreateBy]               INT             NULL,
    [CreateAt]               DATETIME        NULL,
    [LastModifyBy]           INT             NULL,
    [LastModifyAt]           DATETIME        NULL,
    [LastModifyComment]      NVARCHAR (300)  NULL,
    CONSTRAINT [PK_SPCODE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SPCode_SPChannel] FOREIGN KEY ([ChannelID]) REFERENCES [dbo].[SPChannel] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_SPCode_SPCode] FOREIGN KEY ([ParentID]) REFERENCES [dbo].[SPCode] ([ID])
);

