CREATE TABLE [dbo].[SPRecordExtendInfo] (
    [ID]                       INT             IDENTITY (1, 1) NOT NULL,
    [RecordID]                 INT             NOT NULL,
    [IP]                       NVARCHAR (20)   NULL,
    [sSycnDataUrl]             NVARCHAR (300)  NULL,
    [sSycnDataFailedMessage]   NVARCHAR (50)   NULL,
    [sSycnMRDataUrl]           NVARCHAR (300)  NULL,
    [sSycnMRFailedMessage]     NVARCHAR (50)   NULL,
    [sSycnStatusDataUrl]       NVARCHAR (300)  NULL,
    [sSycnStatusFailedMessage] NVARCHAR (50)   NULL,
    [RequestContent]           NVARCHAR (2000) NULL,
    [ExtendField1]             NVARCHAR (50)   NULL,
    [ExtendField2]             NVARCHAR (50)   NULL,
    [ExtendField3]             NVARCHAR (50)   NULL,
    [ExtendField4]             NVARCHAR (50)   NULL,
    [ExtendField5]             NVARCHAR (50)   NULL,
    [ExtendField6]             NVARCHAR (50)   NULL,
    [ExtendField8]             NVARCHAR (50)   NULL,
    [ExtendField7]             NVARCHAR (50)   NULL,
    [ExtendField9]             NVARCHAR (50)   NULL,
    [ExtendField10]            NVARCHAR (50)   NULL,
    [State]                    NVARCHAR (20)   NULL,
    [FeeTime]                  NVARCHAR (3)    NULL,
    [StartTime]                NVARCHAR (20)   NULL,
    [EndTime]                  NVARCHAR (20)   NULL,
    [IsSycnMO]                 BIT             CONSTRAINT [DF_SPRecordExtendInfo_IsSycnMO] DEFAULT ((0)) NOT NULL,
    [IsSycnMR]                 BIT             CONSTRAINT [DF_SPRecordExtendInfo_IsSycnMR] DEFAULT ((0)) NOT NULL,
    [IsSycnState]              BIT             CONSTRAINT [DF_SPRecordExtendInfo_IsSycnState] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_SPRECORDEXTENDINFO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SPRecordExtendInfo_SPRecord] FOREIGN KEY ([RecordID]) REFERENCES [dbo].[SPRecord] ([ID]) ON DELETE CASCADE
);

