// Generated by MyGeneration Version # (1.3.0.9)
using System;
using System.Collections.Generic;
using System.Text;
using NHibernate.Criterion;
using Legendigital.Framework.Common.Data.NHibernate.DynamicQuery;
using Legendigital.Framework.Common.Data.NHibernate.DynamicQuery.Propertys;
using Legendigital.Framework.Common.BaseFramework.Entity.Tables;
using Legendigital.Framework.Common.Data.NHibernate;


namespace Legendigital.Framework.Common.BaseFramework.Data.Tables
{
    public partial class SystemAttachmentDataObject : BaseNHibernateDataObject<SystemAttachmentEntity>
    {
		#region Expression Query Property (标准查询字段)
		public static readonly IntProperty PROPERTY_ID = new IntProperty(Property.ForName(SystemAttachmentEntity.PROPERTY_NAME_ID));		
		public static readonly StringProperty PROPERTY_NAME = new StringProperty(Property.ForName(SystemAttachmentEntity.PROPERTY_NAME_NAME));		
		public static readonly StringProperty PROPERTY_DESCRIPTION = new StringProperty(Property.ForName(SystemAttachmentEntity.PROPERTY_NAME_DESCRIPTION));		
		public static readonly StringProperty PROPERTY_FILENAME = new StringProperty(Property.ForName(SystemAttachmentEntity.PROPERTY_NAME_FILENAME));		
		public static readonly StringProperty PROPERTY_MD5 = new StringProperty(Property.ForName(SystemAttachmentEntity.PROPERTY_NAME_MD5));		
		public static readonly IntProperty PROPERTY_SIZE = new IntProperty(Property.ForName(SystemAttachmentEntity.PROPERTY_NAME_SIZE));		
		public static readonly StringProperty PROPERTY_FILEEXT = new StringProperty(Property.ForName(SystemAttachmentEntity.PROPERTY_NAME_FILEEXT));		
		public static readonly IntProperty PROPERTY_PAGES = new IntProperty(Property.ForName(SystemAttachmentEntity.PROPERTY_NAME_PAGES));		
		public static readonly StringProperty PROPERTY_FILEPATH = new StringProperty(Property.ForName(SystemAttachmentEntity.PROPERTY_NAME_FILEPATH));		
		public static readonly StringProperty PROPERTY_PARENTTYPE = new StringProperty(Property.ForName(SystemAttachmentEntity.PROPERTY_NAME_PARENTTYPE));		
		public static readonly IntProperty PROPERTY_PARENTID = new IntProperty(Property.ForName(SystemAttachmentEntity.PROPERTY_NAME_PARENTID));		
		public static readonly IntProperty PROPERTY_CREATEBY = new IntProperty(Property.ForName(SystemAttachmentEntity.PROPERTY_NAME_CREATEBY));		
		public static readonly DateTimeProperty PROPERTY_CREATEAT = new DateTimeProperty(Property.ForName(SystemAttachmentEntity.PROPERTY_NAME_CREATEAT));		
		public static readonly IntProperty PROPERTY_LASTMODIFYBY = new IntProperty(Property.ForName(SystemAttachmentEntity.PROPERTY_NAME_LASTMODIFYBY));		
		public static readonly DateTimeProperty PROPERTY_LASTMODIFYAT = new DateTimeProperty(Property.ForName(SystemAttachmentEntity.PROPERTY_NAME_LASTMODIFYAT));		
		public static readonly StringProperty PROPERTY_LASTMODIFYCOMMENT = new StringProperty(Property.ForName(SystemAttachmentEntity.PROPERTY_NAME_LASTMODIFYCOMMENT));		
      
		#region 子类集合字段查询字段
	
		#endregion

		#endregion

		
		public override string[] PkPropertyName
        {
            get { return new string[] { "Id" }; }
        }
		
		public override Type GetFieldTypeByFieldName(string fieldName)
        {
			switch (fieldName)
            {
                case "Id":
                    return typeof (int);
                case "Name":
                    return typeof (string);
                case "Description":
                    return typeof (string);
                case "FileName":
                    return typeof (string);
                case "Md5":
                    return typeof (string);
                case "Size":
                    return typeof (int);
                case "FileExt":
                    return typeof (string);
                case "Pages":
                    return typeof (int);
                case "FilePath":
                    return typeof (string);
                case "ParentType":
                    return typeof (string);
                case "ParentID":
                    return typeof (int);
                case "CreateBy":
                    return typeof (int);
                case "CreateAt":
                    return typeof (DateTime);
                case "LastModifyBy":
                    return typeof (int);
                case "LastModifyAt":
                    return typeof (DateTime);
                case "LastModifyComment":
                    return typeof (string);
          }
			return typeof(string);
        }
		
        public override void InClude_Parent_Table(string parent_alias, NHibernateDynamicQueryGenerator<SystemAttachmentEntity> queryGenerator)
        {
            switch (parent_alias)
            {
                default:
                    break;
 
            }
        }
		
		
		

		
		
    }
}
