// Generated by MyGeneration Version # (1.3.0.9)
using System;
using System.Collections.Generic;
using System.Text;
using NHibernate.Criterion;
using Legendigital.Framework.Common.Data.NHibernate.DynamicQuery;
using LD.SPPipeManage.Entity.Tables;
using Legendigital.Framework.Common.Data.NHibernate;

namespace LD.SPPipeManage.Data.Tables
{
    public partial class SPStatReportDataObject
    {
        public SPStatReportEntity FindByChannelIDAndLinkIDAndReportOk(int channelId, string linkid)
        {
            var queryBuilder = new NHibernateDynamicQueryGenerator<SPStatReportEntity>();

            queryBuilder.AddWhereClause(PROPERTY_CHANNELID.Eq(channelId));

            queryBuilder.AddWhereClause(PROPERTY_LINKID.Eq(linkid));

            queryBuilder.AddWhereClause(PROPERTY_ISPAYOK.Eq(true));

            return this.FindSingleEntityByQueryBuilder(queryBuilder);
        }
    }
}
