//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legendigital.Common.Web.Moudles.SPS.Reports {
    
    
    public partial class ReSendData {
        
        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ScriptManagerProxy ScriptManager1;
        
        /// <summary>
        /// viewPortMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ViewPort viewPortMain;
        
        /// <summary>
        /// fitLayoutMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FitLayout fitLayoutMain;
        
        /// <summary>
        /// formResetSycTimes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormPanel formResetSycTimes;
        
        /// <summary>
        /// FormLayoutResetSycTimes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayoutResetSycTimes;
        
        /// <summary>
        /// hidClientChannelID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Hidden hidClientChannelID;
        
        /// <summary>
        /// lblChannleName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Label lblChannleName;
        
        /// <summary>
        /// lblClientName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Label lblClientName;
        
        /// <summary>
        /// hidMaxChangeCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Hidden hidMaxChangeCount;
        
        /// <summary>
        /// numMaxCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.NumberField numMaxCount;
        
        /// <summary>
        /// mfDownCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.MultiField mfDownCount;
        
        /// <summary>
        /// lblDownCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Label lblDownCount;
        
        /// <summary>
        /// btnReSendDown control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button btnReSendDown;
        
        /// <summary>
        /// ToolTip1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ToolTip ToolTip1;
        
        /// <summary>
        /// mfDownNotSycnCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.MultiField mfDownNotSycnCount;
        
        /// <summary>
        /// lblDownNotSycnCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Label lblDownNotSycnCount;
        
        /// <summary>
        /// btnReSendDownNotSycn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button btnReSendDownNotSycn;
        
        /// <summary>
        /// ToolTip2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ToolTip ToolTip2;
        
        /// <summary>
        /// mfSycnCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.MultiField mfSycnCount;
        
        /// <summary>
        /// lblSycnCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Label lblSycnCount;
        
        /// <summary>
        /// btnReSendSycn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button btnReSendSycn;
        
        /// <summary>
        /// ToolTip3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ToolTip ToolTip3;
        
        /// <summary>
        /// mfSycnFailedCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.MultiField mfSycnFailedCount;
        
        /// <summary>
        /// lblSycnFailedCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Label lblSycnFailedCount;
        
        /// <summary>
        /// btnReSendSycnFailed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button btnReSendSycnFailed;
        
        /// <summary>
        /// ToolTip4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ToolTip ToolTip4;
        
        /// <summary>
        /// TaskManager2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.TaskManager TaskManager2;
        
        /// <summary>
        /// winProgress2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Window winProgress2;
        
        /// <summary>
        /// FormLayout1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.FormLayout FormLayout1;
        
        /// <summary>
        /// prgProcess control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.ProgressBar prgProcess;
        
        /// <summary>
        /// btnCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Coolite.Ext.Web.Button btnCancel;
    }
}
