// Generated by MyGeneration Version # (1.3.0.9)
using System;
using System.Collections.Generic;
using System.Text;
using Legendigital.Framework.Common.Bussiness.Interfaces;
using Legendigital.Framework.Common.Data.Interfaces;
using Legendigital.Framework.Common.Bussiness.NHibernate;
using SPS.Data.Tables;
using SPS.Entity.Tables;


namespace SPS.Bussiness.ServiceProxys.Tables
{
	public interface ISPRecordServiceProxy : IBaseSpringNHibernateEntityServiceProxy<SPRecordEntity> ,ISPRecordServiceProxyDesigner
    {
	    void UpdateUrlSuccessSend(int recordId, string url);
	    void UpdateUrlFailedSend(int recordId, string sendUrl, string errorMessage);
    }

    internal partial class SPRecordServiceProxy : ISPRecordServiceProxy
    {
        public void UpdateUrlSuccessSend(int recordId, string url)
        {
            this.AdoNetDb.UpdateUrlSuccessSend(recordId, url);
        }

        public void UpdateUrlFailedSend(int recordId, string sendUrl, string errorMessage)
        {
            this.AdoNetDb.UpdateUrlFailedSend(recordId, sendUrl, errorMessage);
        }
    }
}
