// --------------------------------------------------------------------------------------------------------------------
// <copyright company="foreveross" file="SPRecordExtendInfoServiceProxy.Designer.cs">
//   Copyright (c) Foreveross Enterprises. All rights reserved.
// </copyright>
// <summary>
//   Generated by MyGeneration Version # (1.3.0.9)
// </summary>
// --------------------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using Legendigital.Framework.Common.Bussiness.Interfaces;
using Legendigital.Framework.Common.Data.Interfaces;
using Legendigital.Framework.Common.Data.NHibernate.DynamicQuery;
using Legendigital.Framework.Common.Bussiness.NHibernate;
using SPS.Data.Tables;
using SPS.Entity.Tables;
using SPS.Data.Tables.Container;
using SPS.Data.AdoNet;




namespace SPS.Bussiness.ServiceProxys.Tables
{

    public interface ISPRecordExtendInfoServiceProxyDesigner
    {
		List<SPRecordExtendInfoEntity> FindAllByOrderByAndFilterAndRecordID(string orderByColumnName, bool isDesc,   SPRecordEntity _recordID, PageQueryParams pageQueryParams);
		List<SPRecordExtendInfoEntity> FindAllByRecordID(SPRecordEntity _recordID);
    }

    internal partial class SPRecordExtendInfoServiceProxy //: BaseSpringNHibernateEntityServiceProxy<SPRecordExtendInfoEntity,int>
    {
		public DataObjectContainers DataObjectsContainerIocID { set; get; }
	
        public SPRecordExtendInfoDataObject SelfDataObj
        {
            set
            {
                selfDataObject = value;
            }
			get
            {
                return (SPRecordExtendInfoDataObject)selfDataObject;
            }
        }
	
		public List<SPRecordExtendInfoEntity> FindAllByOrderByAndFilterAndRecordID(string orderByColumnName, bool isDesc,  SPRecordEntity _recordID, PageQueryParams pageQueryParams)
        {
			return this.SelfDataObj.GetPageList_By_RecordID_SPRecordEntity(orderByColumnName, isDesc,_recordID, pageQueryParams);
        }
		
		public List<SPRecordExtendInfoEntity> FindAllByRecordID(SPRecordEntity _recordID)
        {
			return this.SelfDataObj.GetList_By_RecordID_SPRecordEntity(_recordID);
        }




        public AdoNetDataObject AdoNetDb { set; get; }		

		
    }
}
