// Generated by MyGeneration Version # (1.3.0.9)
using System;
using System.Collections.Generic;
using System.Text;
using Legendigital.Framework.Common.Bussiness.Interfaces;
using Legendigital.Framework.Common.Data.Interfaces;
using Legendigital.Framework.Common.Data.NHibernate.DynamicQuery;
using Legendigital.Framework.Common.Bussiness.NHibernate;
using SPS.Data.Tables;
using SPS.Entity.Tables;
using SPS.Data.Tables.Container;
using SPS.Data.AdoNet;




namespace SPS.Bussiness.ServiceProxys.Tables
{

    public interface ISPRecordServiceProxyDesigner
    {
		List<SPRecordEntity> FindAllByOrderByAndFilterAndChannelID(string orderByColumnName, bool isDesc,   SPChannelEntity _channelID, PageQueryParams pageQueryParams);
		List<SPRecordEntity> FindAllByChannelID(SPChannelEntity _channelID);
		List<SPRecordEntity> FindAllByOrderByAndFilterAndClientID(string orderByColumnName, bool isDesc,   SPSClientEntity _clientID, PageQueryParams pageQueryParams);
		List<SPRecordEntity> FindAllByClientID(SPSClientEntity _clientID);
		List<SPRecordEntity> FindAllByOrderByAndFilterAndCodeID(string orderByColumnName, bool isDesc,   SPCodeEntity _codeID, PageQueryParams pageQueryParams);
		List<SPRecordEntity> FindAllByCodeID(SPCodeEntity _codeID);
    }

    internal partial class SPRecordServiceProxy : BaseSpringNHibernateEntityServiceProxy<SPRecordEntity>
    {
		public DataObjectContainers DataObjectsContainerIocID { set; get; }
	
        public SPRecordDataObject SelfDataObj
        {
            set
            {
                selfDataObject = value;
            }
			get
            {
                return (SPRecordDataObject)selfDataObject;
            }
        }
	
		public List<SPRecordEntity> FindAllByOrderByAndFilterAndChannelID(string orderByColumnName, bool isDesc,  SPChannelEntity _channelID, PageQueryParams pageQueryParams)
        {
			return this.SelfDataObj.GetPageList_By_ChannelID_SPChannelEntity(orderByColumnName, isDesc,_channelID, pageQueryParams);
        }
		
		public List<SPRecordEntity> FindAllByChannelID(SPChannelEntity _channelID)
        {
			return this.SelfDataObj.GetList_By_ChannelID_SPChannelEntity(_channelID);
        }
	
		public List<SPRecordEntity> FindAllByOrderByAndFilterAndClientID(string orderByColumnName, bool isDesc,  SPSClientEntity _clientID, PageQueryParams pageQueryParams)
        {
			return this.SelfDataObj.GetPageList_By_ClientID_SPSClientEntity(orderByColumnName, isDesc,_clientID, pageQueryParams);
        }
		
		public List<SPRecordEntity> FindAllByClientID(SPSClientEntity _clientID)
        {
			return this.SelfDataObj.GetList_By_ClientID_SPSClientEntity(_clientID);
        }
	
		public List<SPRecordEntity> FindAllByOrderByAndFilterAndCodeID(string orderByColumnName, bool isDesc,  SPCodeEntity _codeID, PageQueryParams pageQueryParams)
        {
			return this.SelfDataObj.GetPageList_By_CodeID_SPCodeEntity(orderByColumnName, isDesc,_codeID, pageQueryParams);
        }
		
		public List<SPRecordEntity> FindAllByCodeID(SPCodeEntity _codeID)
        {
			return this.SelfDataObj.GetList_By_CodeID_SPCodeEntity(_codeID);
        }




        public AdoNetDataObject AdoNetDb { set; get; }		

		
    }
}
