// Generated by MyGeneration Version # (1.3.0.9)
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Legendigital.Framework.Common.BaseFramework.Entity.Tables
{
	/// <summary>
	///	????????
	/// </summary>
	[DataContract]
	public partial class SystemUserRoleRelationEntity : ICloneable
	{
      #region 公共常量

		public static readonly string CLASS_FULL_NAME = "Legendigital.Framework.Common.BaseFramework.Entity.Tables.SystemUserRoleRelationEntity";
		public static readonly string PROPERTY_NAME_USERROLEID = "UserRoleID";
		public static readonly string PROPERTY_NAME_USERID = "UserID";
		public static readonly string PROPERTY_NAME_ROLEID = "RoleID";
		
        #endregion
	
 
		#region userID字段外键查询字段
        public static readonly string PROPERTY_USERID_ALIAS_NAME = "UserID_SystemUserRoleRelationEntity_Alias";
		public static readonly string PROPERTY_USERID_USERID = "UserID_SystemUserRoleRelationEntity_Alias.UserID";
		public static readonly string PROPERTY_USERID_USERLOGINID = "UserID_SystemUserRoleRelationEntity_Alias.UserLoginID";
		public static readonly string PROPERTY_USERID_USERNAME = "UserID_SystemUserRoleRelationEntity_Alias.UserName";
		public static readonly string PROPERTY_USERID_USEREMAIL = "UserID_SystemUserRoleRelationEntity_Alias.UserEmail";
		public static readonly string PROPERTY_USERID_USERPASSWORD = "UserID_SystemUserRoleRelationEntity_Alias.UserPassword";
		public static readonly string PROPERTY_USERID_USERSTATUS = "UserID_SystemUserRoleRelationEntity_Alias.UserStatus";
		public static readonly string PROPERTY_USERID_USERCREATEDATE = "UserID_SystemUserRoleRelationEntity_Alias.UserCreateDate";
		public static readonly string PROPERTY_USERID_USERTYPE = "UserID_SystemUserRoleRelationEntity_Alias.UserType";
		public static readonly string PROPERTY_USERID_DEPARTMENTID = "UserID_SystemUserRoleRelationEntity_Alias.DepartmentID";
		public static readonly string PROPERTY_USERID_MOBILEPIN = "UserID_SystemUserRoleRelationEntity_Alias.MobilePIN";
		public static readonly string PROPERTY_USERID_PASSWORDFORMAT = "UserID_SystemUserRoleRelationEntity_Alias.PasswordFormat";
		public static readonly string PROPERTY_USERID_PASSWORDQUESTION = "UserID_SystemUserRoleRelationEntity_Alias.PasswordQuestion";
		public static readonly string PROPERTY_USERID_PASSWORDANSWER = "UserID_SystemUserRoleRelationEntity_Alias.PasswordAnswer";
		public static readonly string PROPERTY_USERID_COMMENTS = "UserID_SystemUserRoleRelationEntity_Alias.Comments";
		public static readonly string PROPERTY_USERID_ISAPPROVED = "UserID_SystemUserRoleRelationEntity_Alias.IsApproved";
		public static readonly string PROPERTY_USERID_ISLOCKEDOUT = "UserID_SystemUserRoleRelationEntity_Alias.IsLockedOut";
		public static readonly string PROPERTY_USERID_LASTACTIVITYDATE = "UserID_SystemUserRoleRelationEntity_Alias.LastActivityDate";
		public static readonly string PROPERTY_USERID_LASTLOGINDATE = "UserID_SystemUserRoleRelationEntity_Alias.LastLoginDate";
		public static readonly string PROPERTY_USERID_LASTLOCKEDOUTDATE = "UserID_SystemUserRoleRelationEntity_Alias.LastLockedOutDate";
		public static readonly string PROPERTY_USERID_LASTPASSWORDCHANGEDATE = "UserID_SystemUserRoleRelationEntity_Alias.LastPasswordChangeDate";
		public static readonly string PROPERTY_USERID_FAILEDPWDATTEMPTCNT = "UserID_SystemUserRoleRelationEntity_Alias.FailedPwdAttemptCnt";
		public static readonly string PROPERTY_USERID_FAILEDPWDATTEMPTWNDSTART = "UserID_SystemUserRoleRelationEntity_Alias.FailedPwdAttemptWndStart";
		public static readonly string PROPERTY_USERID_FAILEDPWDANSATTEMPTCNT = "UserID_SystemUserRoleRelationEntity_Alias.FailedPwdAnsAttemptCnt";
		public static readonly string PROPERTY_USERID_FAILEDPWDANSATTEMPTWNDSTART = "UserID_SystemUserRoleRelationEntity_Alias.FailedPwdAnsAttemptWndStart";
		public static readonly string PROPERTY_USERID_ISNEEDCHGPWD = "UserID_SystemUserRoleRelationEntity_Alias.IsNeedChgPwd";
		public static readonly string PROPERTY_USERID_PASSWORDSALT = "UserID_SystemUserRoleRelationEntity_Alias.PasswordSalt";
		public static readonly string PROPERTY_USERID_LOWEREDEMAIL = "UserID_SystemUserRoleRelationEntity_Alias.LoweredEmail";
		public static readonly string PROPERTY_USERID_CREATEBY = "UserID_SystemUserRoleRelationEntity_Alias.CreateBy";
		public static readonly string PROPERTY_USERID_CREATEAT = "UserID_SystemUserRoleRelationEntity_Alias.CreateAt";
		public static readonly string PROPERTY_USERID_LASTMODIFYBY = "UserID_SystemUserRoleRelationEntity_Alias.LastModifyBy";
		public static readonly string PROPERTY_USERID_LASTMODIFYAT = "UserID_SystemUserRoleRelationEntity_Alias.LastModifyAt";
		public static readonly string PROPERTY_USERID_LASTMODIFYCOMMENT = "UserID_SystemUserRoleRelationEntity_Alias.LastModifyComment";
		#endregion
		#region roleID字段外键查询字段
        public static readonly string PROPERTY_ROLEID_ALIAS_NAME = "RoleID_SystemUserRoleRelationEntity_Alias";
		public static readonly string PROPERTY_ROLEID_ROLEID = "RoleID_SystemUserRoleRelationEntity_Alias.RoleID";
		public static readonly string PROPERTY_ROLEID_ROLENAME = "RoleID_SystemUserRoleRelationEntity_Alias.RoleName";
		public static readonly string PROPERTY_ROLEID_ROLECODE = "RoleID_SystemUserRoleRelationEntity_Alias.RoleCode";
		public static readonly string PROPERTY_ROLEID_ROLEDESCRIPTION = "RoleID_SystemUserRoleRelationEntity_Alias.RoleDescription";
		public static readonly string PROPERTY_ROLEID_ROLEISSYSTEMROLE = "RoleID_SystemUserRoleRelationEntity_Alias.RoleIsSystemRole";
		public static readonly string PROPERTY_ROLEID_ROLETYPE = "RoleID_SystemUserRoleRelationEntity_Alias.RoleType";
		public static readonly string PROPERTY_ROLEID_CREATEBY = "RoleID_SystemUserRoleRelationEntity_Alias.CreateBy";
		public static readonly string PROPERTY_ROLEID_CREATEAT = "RoleID_SystemUserRoleRelationEntity_Alias.CreateAt";
		public static readonly string PROPERTY_ROLEID_LASTMODIFYBY = "RoleID_SystemUserRoleRelationEntity_Alias.LastModifyBy";
		public static readonly string PROPERTY_ROLEID_LASTMODIFYAT = "RoleID_SystemUserRoleRelationEntity_Alias.LastModifyAt";
		public static readonly string PROPERTY_ROLEID_LASTMODIFYCOMMENT = "RoleID_SystemUserRoleRelationEntity_Alias.LastModifyComment";
		#endregion
      	
	
	
		 
		
		
		
		
	
        #region 私有成员变量

		private bool _isChanged;		
		private bool _isDeleted;
		
		private int _userRoleID;
		private SystemUserEntity _userID;
		private SystemRoleEntity _roleID;
		
		#endregion

		#region 构造函数
		/// <summary>
		/// 默认构造函数
		/// </summary>
		public SystemUserRoleRelationEntity()
		{
			_userRoleID = 0;
			_userID = null;
			_roleID = null;
		}
		#endregion

		#region 全构造函数
		/// <summary>
		/// 全构造函数
		/// </summary>
		public SystemUserRoleRelationEntity( int userRoleID, SystemUserEntity userID, SystemRoleEntity roleID)
		{
			_userRoleID = userRoleID;
			_userID = userID;
			_roleID = roleID;
		}
		#endregion     
	
	    #region 公共属性

		/// <summary>
		/// ??
		/// </summary>
		[DataMember]
		public virtual int UserRoleID
		{
			get { return _userRoleID; }

			set	
			{
				_isChanged |= (_userRoleID != value); _userRoleID = value;
			}
		}

		/// <summary>
		/// ??ID
		/// </summary>
		[DataMember]
		public virtual SystemUserEntity UserID
		{
			get { return _userID; }

			set	
			{
				_isChanged |= (_userID != value); _userID = value;
			}
		}

		/// <summary>
		/// ??ID
		/// </summary>
		[DataMember]
		public virtual SystemRoleEntity RoleID
		{
			get { return _roleID; }

			set	
			{
				_isChanged |= (_roleID != value); _roleID = value;
			}
		}
		/// <summary>
		/// 返回对象是否被改变。
		/// </summary>
		public virtual bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public virtual bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 

        #region 公共方法
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public virtual void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion

		#region Equals 和 HashCode 方法覆盖
		/// <summary>
		/// local implementation of Equals based on unique value members
		/// </summary>
		public override bool Equals( object obj )
		{
			if( this == obj ) return true;
			
			if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
			
			SystemUserRoleRelationEntity castObj = (SystemUserRoleRelationEntity)obj;
			
			return ( castObj != null ) && ( this._userRoleID == castObj.UserRoleID );
		}
		
		/// <summary>
		/// local implementation of GetHashCode based on unique value members
		/// </summary>
		public override int GetHashCode()
		{
			
			int hash = 57; 
			hash = 27 * hash * _userRoleID.GetHashCode();

			return hash; 
		}
		#endregion
	
		#region ICloneable methods
		
		public virtual object Clone()
		{
			return this.MemberwiseClone();
		}
		
		#endregion
	
	}
}
