// Generated by MyGeneration Version # (1.3.0.9)
using System;
using System.Collections.Generic;
using System.Text;
using NHibernate.Criterion;
using Legendigital.Framework.Common.Data.NHibernate.DynamicQuery;
using SPS.Entity.Tables;
using Legendigital.Framework.Common.Data.NHibernate;

namespace SPS.Data.Tables
{
    public partial class SPRecordDataObject
    {
        public SPRecordEntity CheckChannleLinkIDIsExist(SPChannelEntity spChannelEntity, string linkId)
        {
            var queryBuilder = new NHibernateDynamicQueryGenerator<SPRecordEntity>();

            queryBuilder.AddWhereClause(PROPERTY_CHANNELID.Eq(spChannelEntity));

            queryBuilder.AddWhereClause(PROPERTY_LINKID.Eq(linkId));

            return this.FindSingleEntityByQueryBuilder(queryBuilder);
        }
    }
}
