// Generated by MyGeneration Version # (1.3.0.9)
using System;
using System.Collections.Generic;
using System.Text;
using NHibernate.Criterion;
using Legendigital.Framework.Common.Data.NHibernate.DynamicQuery;
using Legendigital.Framework.Common.BaseFramework.Entity.Tables;
using Legendigital.Framework.Common.Data.NHibernate;

namespace Legendigital.Framework.Common.BaseFramework.Data.Tables
{
    public partial class SystemDictionaryDataObject
    {
        /// <summary>
        /// 根据字典类别名获取该类别下的所有可用的字典项（已排序）
        /// </summary>
        /// <param name="categoryName"></param>
        /// <returns></returns>
        public IList<SystemDictionaryEntity> GetDictionaryByCategoryName(string categoryName)
        {
            NHibernateDynamicQueryGenerator<SystemDictionaryEntity> dynamicQueryGenerator = this.GetNewQueryBuilder();

            dynamicQueryGenerator.AddWhereClause(PROPERTY_SYSTEMDICTIONARYCATEGORYID.Eq(categoryName));

            dynamicQueryGenerator.AddWhereClause(PROPERTY_SYSTEMDICTIONARYISENABLE.Eq(true));

            dynamicQueryGenerator.AddOrderBy(PROPERTY_SYSTEMDICTIONARYORDER.Asc());

            return this.FindListByQueryBuilder(dynamicQueryGenerator);
        }

        /// <summary>
        /// 根据字典类别和字典的key值获取字典项（字典必须可用）
        /// </summary>
        /// <param name="categoryName"></param>
        /// <param name="key"></param>
        /// <returns></returns>
        public SystemDictionaryEntity GetDictionaryByCategoryNameAndKey(string categoryName,string key)
        {
            NHibernateDynamicQueryGenerator<SystemDictionaryEntity> dynamicQueryGenerator = this.GetNewQueryBuilder();

            dynamicQueryGenerator.AddWhereClause(PROPERTY_SYSTEMDICTIONARYCATEGORYID.Eq(categoryName));

            dynamicQueryGenerator.AddWhereClause(PROPERTY_SYSTEMDICTIONARYISENABLE.Eq(true));

            dynamicQueryGenerator.AddWhereClause(PROPERTY_SYSTEMDICTIONARYKEY.Eq(key));

            return this.FindSingleEntityByQueryBuilder(dynamicQueryGenerator);
        }

        /// <summary>
        /// 获取所有的字典类别
        /// </summary>
        /// <returns></returns>
        public List<string> GetAllCategoryNames()
        {
            NHibernateDynamicQueryGenerator<SystemDictionaryEntity> dynamicQueryGenerator = this.GetNewQueryBuilder();
            //Distinct PRIVILEGECATEGORY zi
            return this.FindListByProjection<string>(dynamicQueryGenerator, GetDistinctProperty(PROPERTY_SYSTEMDICTIONARYCATEGORYID.CriterionProperty));
        }
    }
}
